version: '3.8' #version of docker-compose syntax
services:
  top-api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/var/www/.env