version: '3.8' #version of docker-compose syntax
services:
  top-api:
    image: ghcr.io/max-sysoev/top-api/top-api:develop #top-api:latest
    container_name: top-api
    depends_on:
      - 'mongo'
#    network_mode: host
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/var/www/.env
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-data-4.4:/data/db